### ISSUE TITLE
schema directives fail if collection exists

### ISSUE THREAD

**Issue by ujwal-setlur** [cult-of-coders/apollo#36] opened 2018-07-27 00:46 UTC
I am using grapher schema directives to refer to the roles collection created by alanning:rloles package. If the cultofcoders:apollo package is installed after alanning:roles, you run into a server startup exception:

```
W20180726-17:35:12.428(-7)? (STDERR) /Users/ujwal/.meteor/packages/meteor-tool/.1.7.0_3.w8zcf.uowlh++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20180726-17:35:12.513(-7)? (STDERR) 						throw(ex);
W20180726-17:35:12.514(-7)? (STDERR) 						^
W20180726-17:35:12.514(-7)? (STDERR)
W20180726-17:35:12.514(-7)? (STDERR) Error: There is already a collection named "roles"
W20180726-17:35:12.514(-7)? (STDERR)     at ns.Collection.Collection (packages/mongo/collection.js:122:15)
W20180726-17:35:12.515(-7)? (STDERR)     at ns.Collection (packages/matb33_collection-hooks.js:275:27)
W20180726-17:35:12.515(-7)? (STDERR)     at new ns.Collection (packages/lai_collection-extensions.js:107:27)
W20180726-17:35:12.515(-7)? (STDERR)     at setupMongoDirective (packages/cultofcoders:grapher-schema-directives/MongoDirective.js:27:18)
W20180726-17:35:12.515(-7)? (STDERR)     at MongoDirective.visitObject (packages/cultofcoders:grapher-schema-directives/MongoDirective.js:14:5)
W20180726-17:35:12.515(-7)? (STDERR)     at /Users/ujwal/Work/seamlz/seamlz-server/node_modules/graphql-tools/dist/schemaVisitor.js:89:47
W20180726-17:35:12.515(-7)? (STDERR)     at Array.every (<anonymous>)
W20180726-17:35:12.516(-7)? (STDERR)     at callMethod (/Users/ujwal/Work/seamlz/seamlz-server/node_modules/graphql-tools/dist/schemaVisitor.js:88:43)
W20180726-17:35:12.516(-7)? (STDERR)     at visit (/Users/ujwal/Work/seamlz/seamlz-server/node_modules/graphql-tools/dist/schemaVisitor.js:138:29)
W20180726-17:35:12.516(-7)? (STDERR)     at /Users/ujwal/Work/seamlz/seamlz-server/node_modules/graphql-tools/dist/schemaVisitor.js:128:28
W20180726-17:35:12.516(-7)? (STDERR)     at /Users/ujwal/Work/seamlz/seamlz-server/node_modules/graphql-tools/dist/schemaVisitor.js:534:22
W20180726-17:35:12.516(-7)? (STDERR)     at Array.forEach (<anonymous>)
W20180726-17:35:12.516(-7)? (STDERR)     at updateEachKey (/Users/ujwal/Work/seamlz/seamlz-server/node_modules/graphql-tools/dist/schemaVisitor.js:533:32)
W20180726-17:35:12.517(-7)? (STDERR)     at visit (/Users/ujwal/Work/seamlz/seamlz-server/node_modules/graphql-tools/dist/schemaVisitor.js:122:13)
W20180726-17:35:12.517(-7)? (STDERR)     at visitSchema (/Users/ujwal/Work/seamlz/seamlz-server/node_modules/graphql-tools/dist/schemaVisitor.js:214:5)
W20180726-17:35:12.517(-7)? (STDERR)     at Function.SchemaDirectiveVisitor.visitSchemaDirectives (/Users/ujwal/Work/seamlz/seamlz-server/node_modules/graphql-tools/dist/schemaVisitor.js:467:9)
```

So, we need to make sure that cultofcoders:apollo is before alanning:roles in the .meteor/packages file.

**Comment by ujwal-setlur** [comment] 2018-07-27 02:35
I also think this generic to any collection that a previous package installs and we use schema directives referring to those collections

**Comment by ujwal-setlur** [comment] 2018-07-27 05:50
Very true 😄

**Comment by ujwal-setlur** [comment] 2018-07-27 06:06
Actually, that didn't work...

**Comment by theodorDiaconu** [comment] 2018-07-27 06:22
If you run server initialize() in startup do you have the same problem ??

**Comment by ujwal-setlur** [comment] 2018-07-27 07:49
Yes

**Comment by theodorDiaconu** [comment] 2018-07-27 12:45
The problem is with grapher, it needs to load before you load any other packages that may instantiate collections. If you put it as top package, does it still complain ? If not, then we can close this issue.

**Comment by ujwal-setlur** [comment] 2018-07-28 03:07
Yes, specifying grapher at top will resolve the issue, but then this would involve an extra step of installing grapher separately. Moving apollo itself to the top will resolve the issue. I am OK with closing this issue as long as it is documented somewhere that it needs to be at the top.

In grapher, any reasons it can't check whether the collection exists or not?

**Comment by theodorDiaconu** [comment] 2018-08-17 09:49
@ujwal-setlur the problem is that to get the `Mongo.Collection` instances by name we need to hook into the constructor, so we need something like a first package that does this before anything else.

**Closed** 2019-05-08 08:39 UTC
Labels: documentation
